name: rastermap
dependencies:
  - python>=3.7
  - pip
  - numpy>=1.16
  - numba>=0.43.1
  - matplotlib
  - scipy
  - scikit-learn
  - pyqt
  - pip:
    - pyqtgraph
    - natsort
    - scanimage-tiff-reader
    - rastermap>0.1.0